/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class NewtonSuite extends AnyFunSuite {
  test("App has a greeting") {
    assert(Newton != null)
  }
}
